# Generated by Django 4.2.2 on 2023-06-10 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('facebookLink', models.CharField(blank=True, max_length=250, null=True)),
                ('twitterLink', models.CharField(blank=True, max_length=250, null=True)),
                ('instagramLink', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedinLink', models.CharField(blank=True, max_length=250, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
