# Generated by Django 4.2.2 on 2023-06-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
