# Generated by Django 4.2.2 on 2023-06-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_options_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(),
        ),
    ]
