# Generated by Django 4.2.2 on 2023-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tags',
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='PageStatus',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
